variable vpc_id {}
variable avail_zone {}
variable env_prefix {}
variable image_name {}
variable my_ip {}
variable aws_instance_type {}
variable aws_instance_count {}
variable public_key_location {}
variable subnet_id {}
